project:
  type: website
  output-dir: docs

website:
  title: "blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/den-run-ai
      - icon: twitter
        href: https://x.com/den-run-ai
format:
  html:
    theme: cosmo
    css: styles.css



